- type: job
  id: Magistrate
  name: job-name-magistrate
  description: job-description-magistrate
  playTimeTracker: JobMagistrate
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 360000 # Заглушка - 100 часов
    - !type:RoleTimeRequirement
      role: JobIAA
      time: 180000 # Заглушка - 50 часов
    - !type:AgeRequirement
      requiredAge: 32
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
  weight: 20
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  radioBold: true
  access:
  - Command
  - Lawyer
  - Magistrate
  - Service
  - Brig
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: MagistrateGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCommand
    id: MagistratePDA
    ears: ClothingHeadsetAltLaw
  storage:
    back:
    - Flash
