- type: entity
  name: свёкла
  parent: FoodProduceBase
  id: Foodbeet
  description: Сочная и полезная - отличный выбор для салатов и гарниров.
  components:
  - type: FlavorProfile
    flavors:
      - beets
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: Nutriment
          Quantity: 10
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: SS220/Objects/Specific/Hydroponics/beet.rsi
  - type: Produce
    seedId: beet
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuiceBeet
        Quantity: 10

- type: entity
  name: сноп мясопшеницы
  description: Эх... мясопшеница... стоп, что?
  id: MeatwheatBushel
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: SS220/Objects/Specific/Hydroponics/meatwheat.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Blood
          Quantity: 10
        - ReagentId: Nutriment
          Quantity: 5
  - type: Produce
    seedId: meatwheat
  - type: SpawnItemsOnUse
    items:
      - id: FoodMeatWheat
    sound:
      path: /Audio/Effects/Footsteps/slime1.ogg
  - type: Tag
    tags:
    - Meatwheat

- type: entity
  name: листья трикотабакина
  description: Уникальное сочетание табачного листа и тайных специй, создающее неповторимый вкус и аромат. Этот табакин оставляет ощущение удовольствия и умиротворения.
  id: LeavesTricotobacco
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: SS220/Objects/Specific/Hydroponics/tricotobacco.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        reagents:
        - ReagentId: Nicotine
          Quantity: 15
        - ReagentId: Tricordrazine
          Quantity: 10
  - type: Produce
    seedId: tricotobacco
