- type: job
  id: DeathsquadCommander
  name: командир Эскадрона Смерти
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquadCommander
  setPreference: false
  startingGear: DeathSquadLeaderGear
  icon: "JobIconDeathsquadCommander"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: job
  id: DeathsquadHealer
  name: специалист Эскадрона Смерти
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquadHealer
  setPreference: false
  startingGear: DeathSquadHealerGear
  icon: "JobIconDeathsquadHealer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
