- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 # SS220-RoleTime
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-IAA
  canBeAntag: true
  access:
  - Brig
  - Maintenance
#  - Service SS220-Internal-Affairs
  - Detective
  - Lawyer #SS220-Internal-Affairs
  extendedAccess:
  - Security

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetLawyer #SS220-Internal-Affairs
    belt: ClothingBeltHolsterFilled
