- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 72000 # SS220-RoleTime
  startingGear: LawyerGear
  setPreference: true # SS220 return-of-the-lawyer
  icon: "JobIconLawyer"
  supervisors: job-supervisors-IAA
  access:
#  - Service SS220-Internal-Affairs
  - Lawyer
  - Brig
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetLawyer #SS220-InternalAffairs
    ears: 
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw
